version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
    labels:
      - dependencies

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: sunday
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /ui
    schedule:
      interval: weekly
      day: sunday
    labels:
      - dependencies
