name: build

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
        id: go
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.4
      - name: Build
        run: ./build.sh --ci
      - name: Archive binaries
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: "*.tar.gz"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            okr2go-linux-arm64.tar.gz
            okr2go-linux-amd64.tar.gz
            okr2go-darwin-arm64.tar.gz
            okr2go-darwin-amd64.tar.gz
            okr2go-windows-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-docker:
    name: Build Docker
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      - uses: actions/download-artifact@v2
        with:
          path: .
      - name: Build
        run: |
          docker buildx build \
          --platform linux/arm64,linux/amd64 \
          --tag ghrc.io/oxisto/okr2go:latest \
          .
